### ISSUE TITLE
Ruby 2.7 compatibility

### ISSUE THREAD

**Issue by MartinodF** [jonahoffline/filepreviews-ruby#23]
`new_ostruct_member` has been removed from OpenStruct in ruby 2.7.
This breaks [`FilePreviews::Response.responsify`](https://github.com/jonahoffline/filepreviews-ruby/blob/master/lib/filepreviews/response.rb#L21), which relies on it.

This change also impacted rubyconfig/config, and was resolved via rubyconfig/config#255 (by simply removing the method call, if I understand it correctly).

I'm preparing a PR with this change, having tested it in both 2.4.1 and 2.7.1 by running rspec and having no errors. I'm not really sure if this would impact older ruby versions, or something not covered by the specs.

Let me know if you see any issue with this approach!

**Comment by jonahoffline** [comment]
Hi @MartinodF 

This looks great. I tested it against `2.4.1`, `2.5.1`, `2.6.5`, and `2.7.1` and everything is working as expected. Thank you so much, I will be doing a release soon.
