### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by jpadilla** [jonahoffline/filepreviews-ruby#9]
We're getting ready to release v2 of the FilePreviews API. We already have a reference implementation of in https://github.com/GetBlimp/filepreviews-python/pull/3 which we're using to update libraries.

**Comment by jonahoffline** [comment]
Sounds good, I'll check it out asap

**Comment by jonahoffline** [comment]
@jpadilla was just checking out the new implementation changes. When is `v2` going to be available for testing?

**Comment by jpadilla** [comment]
@jonahoffline *ping* :smile:

**Comment by jonahoffline** [comment]
@jpadilla released `2.0.0` to Rubygems 

https://rubygems.org/gems/filepreviews/versions/2.0.0
https://github.com/jonahoffline/filepreviews-ruby/tree/v2.0.0
